# Generated by Django 5.2.13 on 2026-09-09 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(max_length=255, unique=True)),
                ('provider_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('custom_provider_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offering_id', models.CharField(max_length=512, unique=True)),
                ('offering_name', models.CharField(max_length=255)),
                ('service_category', models.CharField(max_length=255)),
                ('part_family', models.CharField(max_length=255)),
                ('support_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('candidate_requiring_confirmation', 'Candidate requiring confirmation'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('supported_part_types', models.JSONField(blank=True, default=list)),
                ('family_capabilities', models.JSONField(blank=True, default=dict)),
                ('part_type_capabilities', models.JSONField(blank=True, default=dict)),
                ('generic_capabilities', models.JSONField(blank=True, default=dict)),
                ('custom_offering_fields', models.JSONField(blank=True, default=dict)),
                ('custom_capability_fields', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id_snapshot', models.CharField(max_length=255)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update')], max_length=16)),
                ('status', models.CharField(choices=[('received', 'Received'), ('validation_failed', 'Validation failed'), ('validated', 'Validated'), ('persisted', 'Persisted'), ('sync_pending', 'Sync pending'), ('synced', 'Synced'), ('sync_failed', 'Sync failed'), ('rejected', 'Rejected')], default='received', max_length=24)),
                ('contract_version', models.CharField(default='1.0', max_length=32)),
                ('submitted_payload', models.JSONField(default=dict)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('submitted_by_external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_errors', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('persisted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=64)),
                ('confidence', models.CharField(max_length=64)),
                ('source_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='providers.provider')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'code'), name='unique_provider_certification')],
            },
        ),
        migrations.CreateModel(
            name='CatalogueSyncEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('provider', 'Provider'), ('offering', 'Offering')], max_length=16)),
                ('entity_id', models.CharField(max_length=512)),
                ('operation', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='providers.providerpublication')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='sync_status_created_idx')],
            },
        ),
    ]
