# Generated by Django 5.2.13 on 2026-09-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='sequence_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='publication_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='providercertification',
            name='sequence_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providercertification',
            name='source_note_present',
            field=models.BooleanField(default=False),
        ),
    ]
