# Generated by Django 5.2.13 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0002_canonical_parity_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerpublication",
            name="operation",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                ],
                max_length=16,
            ),
        ),
    ]
