# Generated by Django 5.2.13 on 2026-09-25

from django.db import migrations, models


def create_catalogue_sync_lease(apps, schema_editor):
    CatalogueSyncLease = apps.get_model("providers", "CatalogueSyncLease")
    CatalogueSyncLease.objects.get_or_create(key="service_discovery_catalogue")


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0003_alter_providerpublication_operation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogueSyncLease",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("owner_token", models.UUIDField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(
            create_catalogue_sync_lease,
            migrations.RunPython.noop,
        ),
    ]
