"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from config.env import env_bool, env_float, env_list
from config.database import database_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#* app level Dirs
PROJECT_ROOT = BASE_DIR.parent

# Canonical local MDC application configuration.
# Deployed/platform environment variables always win over values in .env.
load_dotenv(PROJECT_ROOT / ".env", override=False)

CURATED_DATA_DIR = PROJECT_ROOT / "data" / "curated"
GENERATED_DATA_DIR = PROJECT_ROOT / "data" / "generated"
PROVIDER_SEED_DIR = CURATED_DATA_DIR / "providers"




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Local-only fallback. Production settings require DJANGO_SECRET_KEY explicitly.
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-local-development-only",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)


#! FUSEKI
FUSEKI_BASE_URL = os.getenv(
    "FUSEKI_BASE_URL",
    "http://localhost:3030",
)

FUSEKI_DATASET = os.getenv(
    "FUSEKI_DATASET",
    "mdc",
)

FUSEKI_QUERY_ENDPOINT = os.getenv(
    "FUSEKI_QUERY_ENDPOINT",
    f"{FUSEKI_BASE_URL}/{FUSEKI_DATASET}/sparql",
)

FUSEKI_UPDATE_ENDPOINT = os.getenv(
    "FUSEKI_UPDATE_ENDPOINT",
    f"{FUSEKI_BASE_URL}/{FUSEKI_DATASET}/update",
)

SERVICE_DISCOVERY_FUSEKI_QUERY_ENDPOINT = os.getenv(
    "SERVICE_DISCOVERY_FUSEKI_QUERY_ENDPOINT",
    "",
)

# M7.5 uses the Graph Store Protocol for one-shot default-graph replacement.
# Keep this explicit/blank by default so semantic writes are never inferred from
# a query endpoint or enabled accidentally.
SERVICE_DISCOVERY_FUSEKI_GRAPH_STORE_ENDPOINT = os.getenv(
    "SERVICE_DISCOVERY_FUSEKI_GRAPH_STORE_ENDPOINT",
    "",
).strip()

# Optional secret-backed HTTP Basic authentication for protected Fuseki writes.
# Both values must be supplied together and are kept separate from endpoint URLs.
SERVICE_DISCOVERY_FUSEKI_USERNAME = os.getenv(
    "SERVICE_DISCOVERY_FUSEKI_USERNAME",
    "",
).strip()
SERVICE_DISCOVERY_FUSEKI_PASSWORD = os.getenv(
    "SERVICE_DISCOVERY_FUSEKI_PASSWORD",
    "",
)

FUSEKI_TIMEOUT_SECONDS = env_float("FUSEKI_TIMEOUT_SECONDS", 10)
FUSEKI_SYNC_TIMEOUT_SECONDS = env_float(
    "FUSEKI_SYNC_TIMEOUT_SECONDS",
    FUSEKI_TIMEOUT_SECONDS,
)

MDC_DEMO_API_ENABLED = env_bool("MDC_DEMO_API_ENABLED", True)
MDC_PROVIDER_PUBLICATION_ENABLED = env_bool(
    "MDC_PROVIDER_PUBLICATION_ENABLED",
    True,
)
MDC_PROVIDER_VALIDATION_ENABLED = env_bool(
    "MDC_PROVIDER_VALIDATION_ENABLED",
    False,
)
MDC_CATALOG_SYNC_ENABLED = env_bool(
    "MDC_CATALOG_SYNC_ENABLED",
    False,
)

# M7.6 trusted provider-lifecycle boundary. Local development remains backwards
# compatible by default; production settings override the required flags to true.
MDC_PROVIDER_LIFECYCLE_AUTH_REQUIRED = env_bool(
    "MDC_PROVIDER_LIFECYCLE_AUTH_REQUIRED",
    False,
)
MDC_PROVIDER_LIFECYCLE_SERVICE_TOKEN = os.getenv(
    "MDC_PROVIDER_LIFECYCLE_SERVICE_TOKEN",
    "",
).strip()
MDC_PROVIDER_LIFECYCLE_ACTOR_REQUIRED = env_bool(
    "MDC_PROVIDER_LIFECYCLE_ACTOR_REQUIRED",
    False,
)
MDC_PROVIDER_CONCURRENCY_REQUIRED = env_bool(
    "MDC_PROVIDER_CONCURRENCY_REQUIRED",
    False,
)
MDC_CATALOG_SYNC_PROCESSING_LEASE_SECONDS = env_float(
    "MDC_CATALOG_SYNC_PROCESSING_LEASE_SECONDS",
    900,
)


ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    ["localhost", "127.0.0.1", "[::1]"],
)

# Local development frontend origins.
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        # "http://localhost:5173",
        # "http://127.0.0.1:5173",
    ],
)

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    CORS_ALLOWED_ORIGINS,
)

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "MDC Catalog API",
    "VERSION": "1.0.0",
}


# Application definition

INSTALLED_APPS = [

    #! Project apps
    "apps.api.apps.ApiConfig",
    "apps.catalog.apps.CatalogConfig",
    "apps.ontology.apps.OntologyConfig",
    "apps.providers.apps.ProvidersConfig",
    "apps.search.apps.SearchConfig",
    "apps.demo.apps.DemoConfig",

    
    #* Third-party
    "rest_framework",
    "drf_spectacular",
    "corsheaders",

    #? Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

]

MIDDLEWARE = [

    "corsheaders.middleware.CorsMiddleware",
    #! Django
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {"default": database_config(BASE_DIR, os.getenv("DATABASE_URL"))}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
